services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: flauzino
      POSTGRES_PASSWORD: password
      POSTGRES_DB: assistant
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
